### ISSUE TITLE
At nixpkgs, pkgsMusl.haskellPackages.hslua-core is broken.

### ISSUE THREAD

**Issue by superherointj** [hslua/hslua#132]
At nixpkgs, this package is broken for Musl, errors as:

> hslua-core
>   Core module
>     Error
>       pcall
>         raising an error in the error handler should give a 'double error': Test suite test-hslua-core: FAIL

Full log: https://gist.github.com/superherointj/11db537fdb022ff09605846437dfa992

How meaningful is this?

I'm totally out of context because I'm neither a Haskell nor Lua developer. So I'm just relaying information. (In case someone has a hint that might prove helpful in fixing it.)

Nixpkgs issue: https://github.com/NixOS/nixpkgs/issues/214916

**Comment by tarleb** [comment]
It doesn't seem to matter in practice, I've yet to see an actual bug because of this failure.

It's curious that installing MySQL pulls in this library – probably through pandoc, but that's still weird. But then again, I don't really understand nix, so there might be a good reason. :grin: 

I'm closing this in favor of #106, which is the same issue.
