### ISSUE TITLE
How to build a record with `peek`  functions when reading a table from Lua?

### ISSUE THREAD

**Issue by tchoutri** [hslua/hslua#146]
Hi! I am writing a program whose configuration will be in Lua, and I expect the user to return a table that has roughly this shape:

```lua
local git_deployment = confer.fact({
  name = "git",
  source = "./git",
  destination = "~/"
})

local zsh_deployment = confer.fact({
  name = "zsh",
  sources = {".zsh/", ".zshrc"},
  destination = "~/"
})

local kitty_deployment = confer.fact({
  name = "kitty",
  source = "./kitty",
  destination = "~/.config/"
})

local laptop = confer.deploy({
  hostname = "my-laptop",
  facts = {
    git_deployment,
    zsh_deployment,
    kitty_deployment,
    },
})

local server = confer.deploy({
  hostname = "my-server",
  facts = {
    git_deployment,
    zsh_deployment,
    },
})

return {
  laptop,
  server
}
```

My first intuition is to design the types:

```haskell
data Fact = Fact 
  { name :: Text
  , source :: OsPath
  , destination :: OsPath
  }
  deriving stock (Show, Eq)

data Deployment = Deployment 
  { hostname :: Maybe Text
  , architecture :: Maybe Text
  , os :: Maybe Text
  , facts :: Vector Fact
  }
```

But then I am a bit stuck with how to get the Lua data as Haskell data.
I have something like:

```haskell
module Confer.Config.Evaluator where

import Control.Monad (void)
import Control.Placeholder
import Data.List qualified as List
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Vector (Vector)
import Data.Vector qualified as Vector
import HsLua.Core (Exception)
import HsLua.Core qualified as Lua
import HsLua.Marshalling qualified as Lua
import HsLua.Marshalling.Peek
import System.IO.Unsafe
import System.OsPath qualified as OsPath

import Confer.Config.Types

someFunc :: IO (Result (Vector Deployment))
someFunc = do
  Lua.run $ do
    Lua.openlibs -- load the default Lua packages
    void $ Lua.dofile (Just "./confer.lua")  -- load and run the program
    void $ Lua.getglobal @Exception ""
    Lua.runPeeker todo Lua.top

peekConfig :: Peeker Exception (Vector Deployment)
peekConfig index = Lua.retrieving "config" $ do
  config <- Vector.fromList <$> Lua.peekList (peekDeployment) (Lua.peekText) index
  pure config

peekDeployment :: Peeker Exception Deployment
peekDeployment index = Lua.retrieving "deployment" $ do
  hostname <- Lua.peekNoneOrNilOr (Lua.peekFieldRaw (Lua.peekText) "hostname")
  architecture <- Lua.peekNoneOrNilOr (Lua.peekFieldRaw (Lua.peekText) "architecture")
  os <- Lua.peekNoneOrNilOr (Lua.peekFieldRaw Lua.peekText "os")
  facts <- Lua.peekList peekFact
  pure Deployment{..}
  
peekFact :: Peeker Exception Fact
peekFact index = Lua.retrieving "fact" $ do
  result <- Lua.peekKeyValuePairs (Lua.peekText) (Lua.peekText) index
  pairsToFact result

pairsToFact :: [(Text,Text)] -> Peek Exception Fact
pairsToFact pairs = do
  let name =
        case List.lookup "name" pairs of
          Just n -> n
          Nothing -> error "No name in the fact!"
  let source =
        case List.lookup "source" pairs of
          Just foundSource -> do 
            unsafePerformIO $ OsPath.encodeFS (Text.unpack foundSource)
          Nothing -> error "No source in the fact!"
  let destination =
        case List.lookup "destination" pairs of
          Just foundDestination -> 
            unsafePerformIO $ OsPath.encodeFS (Text.unpack foundDestination)
          Nothing -> error "No destination in the fact!"
  pure Fact{..}
```

But I am actually not sure that all it is the correct way of doing things. Most approaches based on numerical indexes wouldn't work because the indexes are text (so, keys). 

Do you have any advice? Have I missed a function or a pattern in the library to do this?

**Comment by tarleb** [comment]
Looks like a cool project! Yes, that's a roughly the right way to do it, just a few things / minor improvement suggestions: Use `peekNilOr` instead of `peekNoneOrNilOr`, because a type being `None` can only happen in a function call. Also, the nesting of peeker functions should also be slightly different:

``` haskell
peekDeployment :: Peeker Exception Deployment
peekDeployment index = Lua.retrieving "deployment" $ do
  hostname     <- Lua.peekFieldRaw (Lua.NilOr Lua.peekText) "hostname" index
  architecture <- Lua.peekFieldRaw (Lua.NilOr Lua.peekText) "architecture" index
  os           <- Lua.peekFieldRaw (Lua.NilOr Lua.peekText) "os" index
  facts        <- Lua.peekFieldRaw (Lua.peekList peekFact) "facts" index
  pure Deployment{..}
```

I personally prefer that style over the one used for `Fact`.

---

Another simple way is to derive a `FromJSON` instance for your data types and then use `HsLua.Aeson.peekViaJSON`. That's probably only 5 lines of code, but it introduces a dependency on `aeson`.

---

Yet another option is to use is to define a full-blown userdata type and to work with that. Advantage: allows to generate documentation. Disadvantage: probably overkill here. See [here](https://github.com/jgm/pandoc/blob/main/pandoc-lua-engine/src/Text/Pandoc/Lua/Marshal/WriterOptions.hs) for a comparable example.

Please let me know if you run into issues.

**Comment by Kleidukos** [comment]
@tarleb wow, thank you so much for the help!

`FromJSON` is very tempting, and I don't mind the dependency on `aeson`, since I'm distributing a compressed binary in the end. `yaml` would have been a no-go however because it takes so much time to compile. :)

---

Regarding documentation, I think ultimately I want the data to be friendly with the Lua LSP server, so that people can hover on the data and see the expected shape, like in Neovim's configuration:

![image](https://github.com/hslua/hslua/assets/29253044/35159d7e-4fc8-4898-b322-a890d265fb67)

---

I'll keep you up-to-date, I'm really happy that you provide bindings to Lua.

**Comment by tchoutri** [comment]
Very cool approach, I'll probably use the FromJSON encoding. :)

**Comment by tchoutri** [comment]
@tarleb The code is much cleaner:

```haskell
loadConfiguration :: (IOE :> es) => Eff es (Result (Vector Deployment))
loadConfiguration= liftIO $ Lua.run $ do
  Lua.openlibs -- load the default Lua packages
  void $ Lua.dofile (Just "./doc/confer.lua")  -- load and run the program
  Lua.runPeeker peekConfig Lua.top

peekConfig :: Peeker Exception (Vector Deployment)
peekConfig index = Lua.retrieving "config" $ do
  Vector.fromList <$> Lua.peekViaJSON index
```

Now I just have a mismatch of concepts: 

How does the 

```lua
return {
  laptop,
  server
}
```

get returned? It should be a table at the top of the stack, right?

I think I will have to go with the manual parser because the JSON approach doesn't give very useful errors at the moment:

`Failure "failed to decode: parsing [] failed, expected Array, but encountered String" [Name {fromName = "retrieving config"}]`

**Comment by tarleb** [comment]
Error reporting, my nemesis :grimacing: Finding a good balance between simple code, good performance, and informative error handling has been surprisingly difficult. It's true that `peekViaJSON` doesn't have give good errors.

> It should be a table at the top of the stack, right?

Yes, that should work.

**Comment by tchoutri** [comment]
@tarleb Thanks for confirming. I put the project online (https://github.

I'll go with your own style then. :)
